# Simulation --------------------------------------------------------------

# tMax = fin de l'intervalle considéré [0, tMax]
# eta = vecteur (eta1, ..., etad)
# repr = matrice (mu11, mu21, ..., mudd)
# beta = matrice (beta11, ..., betadd)

#' Simulation of a multivariate Hawkes process
#'
#' Simulates a multivariate Hawkes process with exponential reproduction functions. The argument `keep_ancestors` is useful when plotting the patterns with `plot_mhawkes`, but slows the computation. It should be set to `FALSE` if only the simulation matters (and not the cluster structure).
#'
#' @param tMax A double; the end time of the observation window [0,T]
#' @param eta A vector of non-negative doubles; the immigration parameters
#' @param repr A matrix of non-negative doubles; the mean numbers of offsprings
#' @param beta A matrix of non-negative doubles; the rates of the exponential reproduction functions
#' @param keep_ancestors A boolean; track ancestors (used only when plotting the process)
#'
#' @returns A S3 object of class `mhawkes` containing a vector (`.$pointproc`) of simulated values, and all other objects used for the simulation.
#' @export
#'
#' @examples
#' tMax = 10
#' eta = c(2, 1, 3)
#' repr = matrix(runif(9, 0, .33), 3, 3)
#' beta = matrix(rexp(9, 1), 3, 3)
#' x = mhawkes(tMax, eta, repr, beta)
#' plot(x)
mhawkes = function(tMax, eta, repr, beta, keep_ancestors = TRUE) {

  d = length(eta)

  if (d != nrow(repr)) stop("The number of rows in 'repr' should be equal to 'eta's length.")
  if (nrow(repr) != ncol(repr)) stop("'repr' should be a square matrix.")
  if (d != nrow(beta)) stop("The number of rows in 'beta' should be equal to 'eta's length.")
  if (nrow(beta) != ncol(beta)) stop("'beta' should be a square matrix.")

  # Utils function
  genNb = function(x) paste0("gen", x)
  dimNb = function(x) paste0("dim", x)

  # Get immigrants distributed as homogeneous Poisson
  count_immigrants = rpois(d, lambda = eta * tMax)
  immigrants = purrr::map(count_immigrants, ~ runif(., min = 0, max = tMax))
  names(immigrants) = dimNb(1:d)

  # Initialize
  gen = list(gen0=immigrants)
  it = 0

  if (keep_ancestors) ancestors = list()

  # Generate offsprings
  # [[j]]: dimension of offsprings
  # [[j]][[i]]: dimension of parent
  # [[j]][[i]][[n]]: index of parent of dim i
  while (any(purrr::map_int(gen[[genNb(it)]], length))) {

    parents = gen[[genNb(it)]]

    # Iterate over dimension of offsprings
    offsprings = purrr::map(1:d, function(j) {
      # Iterate over dimension of parents
      purrr::map(1:d, function(i) {
        parents_i = parents[[dimNb(i)]]
        count_offsprings = rpois(length(parents_i), lambda = repr[i, j])
        offsprings_ij = purrr::map2(count_offsprings, parents_i,
                             ~ (.y + rexp(.x, rate = beta[i, j])) %>% {.[. < tMax]}
        )
      })
    })

    gen[[genNb(it+1)]] = purrr::map(offsprings, unlist) %>% 'names<-'(dimNb(1:d))

    if (keep_ancestors)
      ancestors[[genNb(it+1)]] = purrr::map(offsprings, function(offsprings_j) {
        purrr::map(1:d, function(i) {
          n = length(parents[[i]])
          count = sapply(offsprings_j[[i]], length)
          if (any(count))
            cbind(i, rep.int(1:n, times = count))
        }) %>% do.call(rbind, .)
      }) %>% 'names<-'(dimNb(1:d))

    it <- it + 1
  }

  # Remove last generation that is always empty (stopping criterion for while loop)
  if (sum(purrr::map_int(gen[[genNb(it)]], length)) == 0) {
    gen[[genNb(it)]] <- NULL
    if (keep_ancestors) ancestors[[genNb(it)]] <- NULL
  }

  # Add all points and sort
  pointproc = purrr::map(1:d, function(k) {
    purrr::map(gen, ~ .[[dimNb(k)]]) %>% unlist(use.names = FALSE) %>% sort() %>% {.[. < tMax]}
  }) %>% 'names<-'(dimNb(1:d))

  # Return object
  if (keep_ancestors)
    hawkes <- list(pointproc = pointproc, tMax = tMax, eta = eta, repr = repr, beta = beta,
                   gen = gen, ancestors = ancestors, call=match.call())
  else
    hawkes <- list(pointproc = pointproc, tMax = tMax, eta = eta, repr = repr, beta = beta,
                   gen = gen, call=match.call())
  class(hawkes) <- "mhawkes"
  return(hawkes)

}

#' Plot of a multivariate Hawkes process
#'
#' Plots the realisation of a multivariate Hawkes process according to its cluster representation. Only works with objects generated from `mhawkes` with argument `keep_ancestors` set to `TRUE`.
#'
#' @param x An object of class `mhawkes`, generated by function `mhawkes`.
#'
#' @returns None
#' @export
plot.mhawkes <- function(x) {

  if (!is(x, "mhawkes")) stop("'plot.mhawkes' is only compatible with Hawkes processes simulated from function 'mhawkes'.")
  if (is.null(x$ancestors)) stop("Member 'ancestors' is missing. Build 'x' using 'mhawkes' and 'keep_ancestors = TRUE'.")

  d = length(x$eta)

  # Utils function
  genNb = function(x) paste0("gen", x)
  dimNb = function(x) paste0("dim", x)

  # Draw a convenient empty plot
  plot(x=NULL, xlim=c(0, x$tMax), ylim=c(-1, length(x$gen)-.5), yaxt="n",
       ylab="Generations", xlab="Time")
  axis(2, at=1:length(x$gen)-1)

  # Add generation 0 (i.e. immigrants)
  for (j in 1:d) {
    points(x=x$gen$gen0[[dimNb(j)]], y=rep(0, length(x$gen$gen0[[dimNb(j)]])), pch = 15, col = j)
  }

  # Add further generations
  eps <- 0.05
  if (length(x$gen) == 1) return()
  for (i in 1:(length(x$gen)-1)) {
    for (j in 1:d) {
      pts = x$gen[[genNb(i)]][[dimNb(j)]]
      if (length(pts)) {
        anc = x$ancestors[[genNb(i)]][[dimNb(j)]]
        points(x = pts, y = rep(i, length(pts)), pch=19, col=j)
        for (n in 1:length(pts)) {
          arrows(x0 = pts[n], x1=x$gen[[genNb(i-1)]][[dimNb(anc[n,1])]][anc[n,2]],
                 y0 = i-eps, y1 = i-1+eps, code=1, length=.1)
        }
      }
    }
  }

}
