# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coinc <- function(x, y, delta) {
    .Call(`_ripley_coinc`, x, y, delta)
}

Coinc <- function(x, y, r) {
    .Call(`_ripley_Coinc`, x, y, r)
}

